description: "Let's vibe \U0001F680"
name: triss25
origin:
  generated: true
  template:
    branch: main
    commit hash: ebfac45e095e206286a62dde2d19124244b5efb3
    cookiecutter:
      _checkout: null
      _repo_dir: /Users/jonzeolla/.cookiecutters/ai-native-python
      _template: gh:zenable-io/ai-native-python
      company_domain: jonzeolla.com
      company_name: jonzeolla
      dockerhub: 'yes'
      github_org: jonzeolla
      license: MIT
      project_name: triss25
      project_owner_github_username: jonzeolla
      project_short_description: "Let's vibe \U0001F680"
      project_slug: triss25
      public: 'yes'
      python_version: '3.13'
    dirty: false
    location: https://github.com/zenable-io/ai-native-python.git
  timestamp: '2025-10-29T15:29:23+00:00'
